version: "3"

services:
  setup_nuc:
    image: ghcr.io/droid-dataset/droid_nuc:${ROBOT_TYPE}
    environment:
      ROBOT_TYPE: ${ROBOT_TYPE}
      NUC_IP: ${NUC_IP}
      ROBOT_IP: ${ROBOT_IP}
      LAPTOP_IP: ${LAPTOP_IP}
    volumes:
      - ${ROOT_DIR}/droid/misc/parameters.py:/app/droid/misc/parameters.py
    build:
      context: ../../
      dockerfile: .docker/nuc/Dockerfile.nuc
      args:
        ROBOT_TYPE: ${ROBOT_TYPE}
        NUC_IP: ${NUC_IP}
        ROBOT_IP: ${ROBOT_IP}
        LAPTOP_IP: ${LAPTOP_IP}
    devices:
      - "/dev:/dev"
    privileged: true
    network_mode: "host"
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      memlock: 102400
    deploy:
      restart_policy:
        condition: any

